# Generated by Django 4.2.2 on 2023-07-29 11:19

from django.db import migrations
import bleach

def clean_post_content(apps, schema_editor):
    Post = apps.get_model('blogs', 'Post')

    additional_tags = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'br', 'p', 'pre', 'span', 'div', 'img', 'table', 'thead', 'tbody', 'tr', 'th', 'td']
    additional_attributes = {
        'a': ['href', 'rel', 'target'],
        'img': ['src', 'alt'],
    }
    ALLOWED_TAGS = bleach.sanitizer.ALLOWED_TAGS.union(additional_tags)
    ALLOWED_ATTRIBUTES = {**bleach.sanitizer.ALLOWED_ATTRIBUTES, **additional_attributes}
    
    for post in Post.objects.all():
        post.content = bleach.clean(
            post.content,
            tags=ALLOWED_TAGS,
            attributes=ALLOWED_ATTRIBUTES,
            strip=False,
        )
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_author_user"),
    ]

    operations = [migrations.RunPython(clean_post_content),]
